apiVersion: v1
kind: Pod
metadata:
  name: pod-ubuntu-sleeper
  namespace: dev  # if not specified, it will be `Default`
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"]  # overrides the Dockerfile instruction `ENTRYPOINT["sleep]`
      args: ["10"]  # overrides the Dockerfile instruction `CMD["5"]`

      # Alternative syntax:
      # command:
      #  - "sleep"
      #  - "10"
