apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp  # labels of the ReplicaSet itself
    function: front-end
  annotations:  # used for information purposes
    name: Viacheslav Kolupaev
    buildversion: 0.1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3  # number of replicas
  template:  # POD template to be replicated
    metadata:
      name: nginx-2
      labels:
        app: myapp  # labels of the pod
    spec:
      containers:
        - name: nginx
          image: nginx
