apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:  # the "-" symbol indicates the start of a new rule
          matchLabels:
            name: api-pod
        namespaceSelector:  # if you add a "-" symbol, then this will be another rule
          matchLabels:
            name: prod
      - ipBlock:  # the "-" symbol indicates the start of a new rule
          cidr: 192.168.1.5/32
      ports:
        - protocol: TCP
          port: 3306
  egress:
    - to:
      - ipBlock: # the "-" symbol indicates the start of a new rule
          cidr: 192.168.1.5/32
      ports:
        - protocol: TCP
          port: 80

    - to:
        - podSelector:
            matchLabels:
              name: mysql
      ports:
        - protocol: TCP
          port: 3306

    - to:
        - podSelector:
            matchLabels:
              name: payroll
      ports:
        - protocol: TCP
          port: 8080

    # To ensure that the internal DNS resolution works from the internal pod.
    # The kube-dns service is exposed on port 53.
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
