apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: dev  # if not specified, it will be `default`
  labels:
    app: webapp
    tier: backend
spec:
  securityContext:  # these settings will apply to all containers of this Pod
    runAsUser:  1000
  serviceAccountName: my-src-sa  # custom service-account
  # automountServiceAccountToken: false
  containers:
    - name: webapp
      image: webapp
      ports:
        - containerPort: 8080

      # Docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
      readinessProbe:
        # Option 1: HTTP request
        httpGet:
          port: 8080
          path: /api/v1/ready

        # Option 2: TCP probe
        tcpSocket:
          port: 3306

        # Option 3: custom command
        exec:
          command:
            - cat
            - /src/is_ready

        # Delay and repeat settings.
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3

      livenessProbe:
        # Option 1: HTTP request
        httpGet:
          port: 8080
          path: /api/v1/healthy


        # Option 2: TCP liveness probe
        tcpSocket:
          port: 3306

        # Option 3: custom command
        exec:
          command:
            - cat
            - /src/is_healthy

        # Delay and repeat settings.
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3

    - name: postgres
      image: postgres
      command: ["sleep"]  # overrides the Dockerfile instruction `ENTRYPOINT["sleep]`
      args: ["10"]  # overrides the Dockerfile instruction `CMD["5"]`
      securityContext:
        runAsUser:  1000
        capabilities:  # only supported at the container level
          add:
            - "MAC_ADMIN"

      # environment variables options
      envFrom:  # inject everything from env file
        - configMapRef:
            name: my_config_map  # need to be created in my_config_map.yaml

        # All secrets from .yaml
        - secretRef:
            name: my-app-secret  # refers to my_app_secret_data.yaml
      env:  # inject only one key-value pair
        # Plain Key Value
        - name: POSTGRES_PASSWORD
          value: mysecretpassword

        # ConfigMap
        - name: KEY_1
          valueFrom:
            configMapKeyRef:
              name: my_config_map
              key: KEY_1

        # Single secret from .yaml
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-app-secret  # refers to my_app_secret_data.yaml
              key: DB_USER
      # Resource Requests
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
      volumeMounts:
        - mountPath: "/opt/dir_1"
          name: dir_1
  restartPolicy: Always  # Always (default) / Never / OnFailure
  tolerations:
    # Use double quotes
    - key: "src"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  volumes:
    - name: my-src-secret-volume
      secret:
        secretName: my-app-secret
        # ls /opt/my-src-secret-volumes
        # cat /opt/my-src-secret-volumes/DB_USER
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
  nodeSelector:
    size: Large
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: Exists
              - key: size
                operator: In
                values:
                  - Large
                  - Medium
              - key: size
                operator: NotIn
                values:
                  - Small
