apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80  # Service port inside the node
      targetPort: 80 # POD port inside node
      nodePort: 30004  # Node external port; 30000 - 32767
  selector:
    app: web-store  # see deployment.yaml → spec → template → metadata → labels → src
    type: front-end
