---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80  # Service port inside the node
      targetPort: 80 # POD port inside node
      protocol: TCP
      nodePort: 30004  # Node external port; 30000 - 32767
      name: http
    - port: 443  # Service port inside the node
      targetPort: 443 # POD port inside node
      protocol: TCP
      name: https
  selector:
    app: web-store  # see deployment.yaml → spec → template → metadata → labels → src
    type: front-end
...
